[build]
command = "hugo --gc --minify -b $URL"

[context.production.environment]
HUGO_VERSION = "0.88.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.88.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.88.1"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.88.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://quincychange.org/*"
  to = "https://qftc.org/:splat"
  force = true

[[redirects]]
  from = "https://www.quincychange.org/*"
  to = "https://qftc.org/:splat"
  force = true

[[redirects]]
  from = "https://quincy4change.org/*"
  to = "https://qftc.org/:splat"
  force = true

[[redirects]]
  from = "https://www.quincy4change.org/*"
  to = "https://qftc.org/:splat"
  force = true
